### ISSUE TITLE
ParticleBuilder crash in whirlpool spell

### ISSUE THREAD

**Issue by Electroblob77** [FavouriteDragon/Arcane-Essentials#10]
Forwarding from wizardry's issue tracker, see https://github.com/Electroblob77/Wizardry/issues/325

Pretty sure this is because you're spawning particles from a render class.

**Comment by FavouriteDragon** [comment]
Shhhhhhh it's 10000% fine
It's fixed regardless :P

**Comment by m-vlad** [comment]
Not fixed yet apparently.
```Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at com.favouritedragon.arcaneessentials.common.util.ArcaneUtils.spawnSpinningVortex(ArcaneUtils.java:230)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70106_y(EntityWhirlpool.java:146)
	at electroblob.wizardry.entity.construct.EntityMagicConstruct.despawn(EntityMagicConstruct.java:80)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.despawn(EntityMagicConstruct.java:82)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.func_70071_h_(EntityMagicConstruct.java:75)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70071_h_(EntityWhirlpool.java:68)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@55f8669d from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.favouritedragon.arcaneessentials.common.util.ArcaneUtils.spawnSpinningVortex(ArcaneUtils.java:230)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70106_y(EntityWhirlpool.java:146)
	at electroblob.wizardry.entity.construct.EntityMagicConstruct.despawn(EntityMagicConstruct.java:80)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.despawn(EntityMagicConstruct.java:82)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.func_70071_h_(EntityMagicConstruct.java:75)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70071_h_(EntityWhirlpool.java:68)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: arcane_essentials:whirlpool (com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool)
	Entity ID: 950416
	Entity Name: entity.arcane_essentials:whirlpool.name
	Entity's Exact location: -1065.30, 104.63, -329.15
	Entity's Block location: World: (-1066,104,-330), Chunk: (at 6,6,6 in -67,-21; contains blocks -1072,0,-336 to -1057,255,-321), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)```

**Comment by The-Minecraft-Scientist** [comment]
that crash was caused by a typo involving a particle rendering for loop missing a starting bracket, presumably bringing it out of the if statement that _should_ have kept it from trying to render particles on the server side
