### ISSUE TITLE
NullPointerException from evil wizard

### ISSUE THREAD

**Issue by Eonasdan** [FavouriteDragon/Arcane-Essentials#11]
EW Version: 4.2.7
AE Version: 0.9.2

java.lang.NullPointerException: Ticking entity
	at com.favouritedragon.arcaneessentials.common.spell.necromancy.Zam.onEntityHit(Zam.java:38)
	at electroblob.wizardry.spell.SpellRay.cast(SpellRay.java:183)
	at electroblob.wizardry.entity.living.EntityAIAttackSpell.attemptCastSpell(EntityAIAttackSpell.java:216)
	at electroblob.wizardry.entity.living.EntityAIAttackSpell.func_75246_d(EntityAIAttackSpell.java:191)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at electroblob.wizardry.entity.living.EntityEvilWizard.func_70636_d(EntityEvilWizard.java:198)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by FavouriteDragon** [comment]
Fixed!

**Comment by Lgmrszd** [comment]
Hello. I've encountered similar crash, here's link to the log: https://gist.github.com/Lgmrszd/b903458f82da71ad4364ac1e9697dc3a
