### ISSUE TITLE
Server crashes after using Vortex related spells in certain instances.

### ISSUE THREAD

**Issue by BlueYoshi68** [FavouriteDragon/Arcane-Essentials#14]
Using the latest version of both EB and Arcane.
`Description: Ticking entity

java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at com.favouritedragon.arcaneessentials.common.util.ArcaneUtils.spawnSpinningVortex(ArcaneUtils.java:230)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70106_y(EntityWhirlpool.java:146)
	at electroblob.wizardry.entity.construct.EntityMagicConstruct.despawn(EntityMagicConstruct.java:80)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.despawn(EntityMagicConstruct.java:82)
	at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.func_70071_h_(EntityMagicConstruct.java:75)
	at com.favouritedragon.arcaneessentials.common.entity.EntityWhirlpool.func_70071_h_(EntityWhirlpool.java:68)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4a55a6e8 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 18 more
Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 20 more`

**Comment by FavouriteDragon** [comment]
This is a known bug, it'll be fixed in the next update

**Comment by HeyZeer0** [comment]
Fixed in #15

**Comment by FavouriteDragon** [comment]
Got an update out
