### ISSUE TITLE
Arcane Essentials doesn't work in my Modpack.

### ISSUE THREAD

**Issue by FlareStormGaming** [FavouriteDragon/Arcane-Essentials#54]
I have a large modpack which is a version of RLCraft with like fifty extra mods, and I was going to add EBW and Arcane Essentials for Roleplay ability. However, my game crashes before even finishing loading the mods with the following errors: 
-- Head --
Thread: Client thread
Stacktrace:
    at com.favouritedragon.arcaneessentials.common.spell.air.CycloneBolt.<init>(CycloneBolt.java:23)
    at com.favouritedragon.arcaneessentials.RegisterHandler.register(RegisterHandler.java:86)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_302_RegisterHandler_register_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    
    -- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

As you can see, I'm using MultiMC. I've attached a text file with all the mods I'm using. 
[message.txt](https://github.com/FavouriteDragon/Arcane-Essentials/files/5973526/message.txt)

**Comment by FlareStormGaming** [comment]
Keep in mind, i'm using Arcane Essentials 0.9.2 because at the time I was unaware that 1.0.0-alpha-6 was compatible with EBW 4.2.11
