### ISSUE TITLE
mod crashes my client

### ISSUE THREAD

**Issue by CobaltGlacier** [FavouriteDragon/Arcane-Essentials#60]
i keep crashing when i run this mod, could someone please look into this crash log?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 8/7/21 10:45 AM
Description: Initializing game

java.lang.NoSuchMethodError: electroblob.wizardry.spell.SpellRay.<init>(Ljava/lang/String;Ljava/lang/String;ZLnet/minecraft/item/EnumAction;)V
	at com.favouritedragon.arcaneessentials.common.spell.SpellRay.<init>(SpellRay.java:25)
	at com.favouritedragon.arcaneessentials.common.spell.ice.BlizzardBeam.<init>(BlizzardBeam.java:29)
	at com.favouritedragon.arcaneessentials.RegisterHandler.register(RegisterHandler.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_215_RegisterHandler_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.favouritedragon.arcaneessentials.common.spell.SpellRay.<init>(SpellRay.java:25)
	at com.favouritedragon.arcaneessentials.common.spell.ice.BlizzardBeam.<init>(BlizzardBeam.java:29)
	at com.favouritedragon.arcaneessentials.RegisterHandler.register(RegisterHandler.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_215_RegisterHandler_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561108552 bytes (535 MB) / 1195376640 bytes (1140 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                        | Signature                                |
	|:----- |:----------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2855      | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | baubles           | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | ebwizardry        | 4.3.4             | ElectroblobsWizardry-4.3.4-MC1.12.2.jar       | None                                     |
	| LCH   | arcane_essentials | 1.0               | Arcane Essentials-0.9.2.jar                   | None                                     |
	| LCH   | ctm               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCH   | minerva           | 1.0.13            | minerva-library-1.0.13.jar                    | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCH   | extraalchemy      | 0.5.4             | extraalchemy-forge-1.12-build11-0.5.4.jar     | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCH   | golems            | 7.1.9             | ExtraGolems-1.12-7.1.9.jar                    | None                                     |
	| LCH   | potioncore        | 1.9_for_1.12.2    | PotionCore-1.9_for_1.12.2.jar                 | None                                     |
	| LCH   | extra_spells      | 1.2.0             | ExtraSpells-1.12.2-1.2.0.jar                  | None                                     |
	| LCH   | patchouli         | 1.0-23.6          | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCH   | twilightforest    | 3.11.1021         | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCH   | tfspellpack       | 1.1.0             | TFSpellPack-1.1.0-MC1.12.2.jar                | None                                     |
	| LCH   | wizardrygolems    | 1.2.0             | WizardryGolems-1.1.0.jar                      | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.11' Renderer: 'NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by MagmaBro123** [comment]
See #65. The 'Ray' spell is the issue.
