### ISSUE TITLE
Saintless Sun seems to be buggy on servers.

### ISSUE THREAD

**Issue by SfortzaPhantom** [FavouriteDragon/Arcane-Essentials#69]
See crash report for reference.

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-04-03 00:27:05 MSK
Description: Ticking entity

java.lang.NoSuchMethodError: com/favouritedragon/arcaneessentials/common/entity/EntityMagicConstruct.func_70016_h(DDD)V (loaded from jar:file:/C:/Users/User/Desktop/Minecraft%20(ngrok)/./mods/arcane_essentials-1.0.1.jar!/com/favouritedragon/arcaneessentials/common/entity/EntityMagicConstruct.class by net.minecraft.launchwrapper.LaunchClassLoader@b60edccf) called from class com.favouritedragon.arcaneessentials.common.spell.divine.SaintessSun$SaintessSunBehaviour (loaded from jar:file:/C:/Users/User/Desktop/Minecraft%20(ngrok)/./mods/arcane_essentials-1.0.1.jar!/com/favouritedragon/arcaneessentials/common/spell/divine/SaintessSun$SaintessSunBehaviour.class by net.minecraft.launchwrapper.LaunchClassLoader@b60edccf).
    at com.favouritedragon.arcaneessentials.common.spell.divine.SaintessSun$SaintessSunBehaviour.onUpdate(SaintessSun.java:125)
    at com.favouritedragon.arcaneessentials.common.spell.divine.SaintessSun$SaintessSunBehaviour.onUpdate(SaintessSun.java:112)
    at com.favouritedragon.arcaneessentials.common.entity.EntityMagicConstruct.func_70071_h_(EntityMagicConstruct.java:115)
    at com.favouritedragon.arcaneessentials.common.entity.EntitySaintessSun.func_70071_h_(EntitySaintessSun.java:51)
    at net.minecraft.world.World.func_72866_a(World.java:1996)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1958)
    at net.minecraft.world.World.redirect$zbi000$updateEntity(World.java:5123)
    at net.minecraft.world.World.func_72939_s(World.java:1762)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:823)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: arcane_essentials:saintesssun (com.favouritedragon.arcaneessentials.common.entity.EntitySaintessSun)
  Entity ID: 403
  Entity Name: entity.arcane_essentials:saintesssun.name
  Entity's Exact location: -1336,03, 80,00, 652,17
  Entity's Block location: World: (-1337,80,652), Chunk: (at 7,5,12 in -84,40; contains blocks -1344,0,640 to -1329,255,655), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
  Entity's Momentum: 0,00, 0,00, 0,00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],UUIDLeast:-6390361902363395409L,lifetime:140,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,damageMultiplier:1.0f,FallDistance:0.0f,UUIDMost:4422720713749316211L,Pos:[-1336.0282576585748d,80.0d,652.1726529304863d],Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}},casterUUIDLeast:-7861842765672377617L,casterUUIDMost:-1803889899932602311L}

```

**Comment by WinDanesz** [comment]
Please test with v1.0.3, should be fixed.
Open a new issue with a new crash log if it reoccurs
