### ISSUE TITLE
Server crash in EntityCycloneShield with NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V

### ISSUE THREAD

**Issue by LemADEC** [FavouriteDragon/Arcane-Essentials#7]
As of ElectroblobsWizardry-4.2.5 + Arcane Essentials-0.9.2, server is crashing due to invalid calls to setVelocity() on server side.
Entity:setVelocity() is client side only.

```
[05:15:13] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.func_70016_h(DDD)V
>       at com.favouritedragon.arcaneessentials.common.entity.EntityCycloneShield.func_70071_h_(EntityCycloneShield.java:145) ~[EntityCycloneShield.class:?]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:167) ~[spongeforge-1.12.2-2838-7.1.8-RC3957.jar:1.12.2-2838-7.1.8-RC3957]
>       at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zll000(WorldServer.java:4740) ~[oo.class:?]
>       at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
>       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
>       at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3930) ~[oo.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
>       ... 4 more
```

**Comment by FavouriteDragon** [comment]
fixed, will be in the next update
